@include('partials.elemento_lista', ['tipo_mat' => $songs, 'titulo_mat' => 'Audios', 'etiqueta' => 'audios'])
@include('partials.elemento_lista', ['tipo_mat' => $videos, 'titulo_mat' => 'Videos', 'etiqueta' => 'videos'])
@include('partials.elemento_lista', ['tipo_mat' => $links, 'titulo_mat' => 'Links', 'etiqueta' => 'links'])
@include('partials.elemento_lista_where', ['clasif' => 'Reactivos adicionales', 'etiqueta' => 'reactivos'])
@include('partials.elemento_lista_where', ['clasif' => 'Guia del docente', 'etiqueta' => 'guia'])
@include('partials.elemento_lista_where', ['clasif' => 'Conoce más', 'etiqueta' => 'conoce'])
@include('partials.elemento_lista_where', ['clasif' => 'Cuadernillo de tareas', 'etiqueta' => 'cuadernillo'])
@include('partials.elemento_lista_where', ['clasif' => 'Evaluación diagnostica', 'etiqueta' => 'evaluacion'])
@include('partials.elemento_lista_where', ['clasif' => 'ECAS', 'etiqueta' => 'ecas'])
@include('partials.elemento_lista_where', ['clasif' => 'Recursos adicionales', 'etiqueta' => 'recursos'])
@include('partials.elemento_lista_where', ['clasif' => 'Cuadernillo de actividades de acuerdo al nuevo modelo educativo con y sin respuestas', 'etiqueta' => 'actividades'])
@include('partials.elemento_lista_where', ['clasif' => 'Habilidades socioeconomicas', 'etiqueta' => 'habilidades'])
@include('partials.elemento_lista_where', ['clasif' => 'Planes y programas vigentes', 'etiqueta' => 'planes'])
@include('partials.elemento_lista_where', ['clasif' => 'Talleres para personal docente', 'etiqueta' => 'talleres'])
@include('partials.elemento_lista_where', ['clasif' => 'Para saber más', 'etiqueta' => 'saber'])
@include('partials.elemento_lista_where', ['clasif' => 'Teacher book', 'etiqueta' => 'teacher'])
@include('partials.elemento_lista_where', ['clasif' => 'Evaluaciones IGRADE', 'etiqueta' => 'igrade'])