@include('partials.tab_contenido', ['nombre' => 'Reactivos adicionales', 'etiqueta' => 'reactivos']) 
@include('partials.tab_contenido', ['nombre' => 'Guia del docente', 'etiqueta' => 'guia'])   
@include('partials.tab_contenido', ['nombre' => 'Conoce más', 'etiqueta' => 'conoce'])  
@include('partials.tab_contenido', ['nombre' => 'Cuadernillo de tareas', 'etiqueta' => 'cuadernillo'])  
@include('partials.tab_contenido', ['nombre' => 'Evaluación diagnostica', 'etiqueta' => 'evaluacion'])  
@include('partials.tab_contenido', ['nombre' => 'ECAS', 'etiqueta' => 'ecas'])  
@include('partials.tab_contenido', ['nombre' => 'Recursos adicionales', 'etiqueta' => 'recursos'])  
@include('partials.tab_contenido', ['nombre' => 'Cuadernillo de actividades de acuerdo al nuevo modelo educativo con y sin respuestas', 'etiqueta' => 'actividades'])  
@include('partials.tab_contenido', ['nombre' => 'Habilidades socioeconomicas', 'etiqueta' => 'habilidades'])  
@include('partials.tab_contenido', ['nombre' => 'Planes y programas vigentes', 'etiqueta' => 'planes'])  
@include('partials.tab_contenido', ['nombre' => 'Talleres para personal docente', 'etiqueta' => 'talleres'])  
@include('partials.tab_contenido', ['nombre' => 'Para saber más', 'etiqueta' => 'saber'])  
@include('partials.tab_contenido', ['nombre' => 'Teacher book', 'etiqueta' => 'teacher'])  
@include('partials.tab_contenido', ['nombre' => 'Evaluaciones IGRADE', 'etiqueta' => 'igrade'])